#spring.profiles: integration
# use local or embedded mongodb at localhost:27017
---
#spring.profiles: production
#spring.data.mongodb.uri: mongodb+srv://admin:admin123@cluster0-z3dgq.mongodb.net/test?retryWrites=true
#mongodb://<user>:<passwd>@<url>:<port>/<dbname>

spring.data.mongodb.uri: mongodb://admin:admin123@cluster0-shard-00-00-z3dgq.mongodb.net:27017,cluster0-shard-00-01-z3dgq.mongodb.net:27017,cluster0-shard-00-02-z3dgq.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true